///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelUser {
/*
{
  "id": 84,
  "firstname": "demo",
  "lastname": "user",
  "location": "India",
  "phone": "8080156829",
  "phonecode": "91",
  "email": "demo@gmail.com",
  "date_of_birth": "1990-01-01",
  "gender": "male",
  "referral_code": "djbdj",
  "user_referral_code": "IYV4Yc",
  "profile_image": "noimage",
  "id_front": "--",
  "id_back": "--",
  "lat": null,
  "lng": null,
  "status": "active",
  "fcm_token": null,
  "created_at": "2024-09-02T19:11:27.000000Z",
  "updated_at": "2024-09-02T19:11:27.000000Z",
  "name": "demo user",
  "phone_wcode": "+91 8080156829",
  "age": 34,
  "is_register_q_done": 0,
  "total_earnings": 0
} 
*/

  int? id;
  String? firstname;
  String? lastname;
  String? location;
  String? phone;
  String? phonecode;
  String? email;
  String? dateOfBirth;
  String? gender;
  String? referralCode;
  String? userReferralCode;
  String? profileImage;
  String? idFront;
  String? idBack;
  String? lat;
  String? lng;
  String? status;
  String? fcmToken;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? phoneWcode;
  int? age;
  int? isRegisterQDone;
  int? totalEarnings;

  LoginModelUser({
    this.id,
    this.firstname,
    this.lastname,
    this.location,
    this.phone,
    this.phonecode,
    this.email,
    this.dateOfBirth,
    this.gender,
    this.referralCode,
    this.userReferralCode,
    this.profileImage,
    this.idFront,
    this.idBack,
    this.lat,
    this.lng,
    this.status,
    this.fcmToken,
    this.createdAt,
    this.updatedAt,
    this.name,
    this.phoneWcode,
    this.age,
    this.isRegisterQDone,
    this.totalEarnings,
  });
  LoginModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    location = json['location']?.toString();
    phone = json['phone']?.toString();
    phonecode = json['phonecode']?.toString();
    email = json['email']?.toString();
    dateOfBirth = json['date_of_birth']?.toString();
    gender = json['gender']?.toString();
    referralCode = json['referral_code']?.toString();
    userReferralCode = json['user_referral_code']?.toString();
    profileImage = json['profile_image']?.toString();
    idFront = json['id_front']?.toString();
    idBack = json['id_back']?.toString();
    lat = json['lat']?.toString();
    lng = json['lng']?.toString();
    status = json['status']?.toString();
    fcmToken = json['fcm_token']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    name = json['name']?.toString();
    phoneWcode = json['phone_wcode']?.toString();
    age = json['age']?.toInt();
    isRegisterQDone = json['is_register_q_done']?.toInt();
    totalEarnings = json['total_earnings']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['location'] = location;
    data['phone'] = phone;
    data['phonecode'] = phonecode;
    data['email'] = email;
    data['date_of_birth'] = dateOfBirth;
    data['gender'] = gender;
    data['referral_code'] = referralCode;
    data['user_referral_code'] = userReferralCode;
    data['profile_image'] = profileImage;
    data['id_front'] = idFront;
    data['id_back'] = idBack;
    data['lat'] = lat;
    data['lng'] = lng;
    data['status'] = status;
    data['fcm_token'] = fcmToken;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['name'] = name;
    data['phone_wcode'] = phoneWcode;
    data['age'] = age;
    data['is_register_q_done'] = isRegisterQDone;
    data['total_earnings'] = totalEarnings;
    return data;
  }
}

class LoginModel {
/*
{
  "status": true,
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGFzdGVsaW5rLnBpbGxlcnNvZnR0ZWNobm9sb2dpZXMuY29tL2FwaS91c2VyL2xvZ2luIiwiaWF0IjoxNzI1MzA0MzQxLCJleHAiOjE3MjU0NjM5NDEsIm5iZiI6MTcyNTMwNDM0MSwianRpIjoiUVI0UWlCQ0laeXhhMkEyeCIsInN1YiI6Ijg0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.7bARUfXVVWkoshMxRQmB8uxX1pUw2mvQIKEOTdJlxNI",
  "user": {
    "id": 84,
    "firstname": "demo",
    "lastname": "user",
    "location": "India",
    "phone": "8080156829",
    "phonecode": "91",
    "email": "demo@gmail.com",
    "date_of_birth": "1990-01-01",
    "gender": "male",
    "referral_code": "djbdj",
    "user_referral_code": "IYV4Yc",
    "profile_image": "noimage",
    "id_front": "--",
    "id_back": "--",
    "lat": null,
    "lng": null,
    "status": "active",
    "fcm_token": null,
    "created_at": "2024-09-02T19:11:27.000000Z",
    "updated_at": "2024-09-02T19:11:27.000000Z",
    "name": "demo user",
    "phone_wcode": "+91 8080156829",
    "age": 34,
    "is_register_q_done": 0,
    "total_earnings": 0
  },
  "message": "Login Successful"
} 
*/

  bool? status;
  String? token;
  LoginModelUser? user;
  String? message;

  LoginModel({
    this.status,
    this.token,
    this.user,
    this.message,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    token = json['token']?.toString();
    user =
        (json['user'] != null) ? LoginModelUser.fromJson(json['user']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['token'] = token;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
