///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaymentDetailResponseNotes {
/*
{
  "ok": "done"
} 
*/

  String? ok;

  PaymentDetailResponseNotes({
    this.ok,
  });
  PaymentDetailResponseNotes.fromJson(Map<String, dynamic> json) {
    ok = json['ok']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ok'] = ok;
    return data;
  }
}

class PaymentDetailModel {
/*
{
  "id": "order_LmJwi5Y8UGvw7z",
  "entity": "order",
  "amount": 1000,
  "amount_paid": 0,
  "amount_due": 1000,
  "currency": "INR",
  "receipt": "rcptid_11",
  "offer_id": null,
  "status": "created",
  "attempts": 0,
  "notes": [
    {
      "ok": "done"
    }
  ],
  "created_at": 1683363788
} 
*/

  String? id;
  String? entity;
  int? amount;
  int? amountPaid;
  int? amountDue;
  String? currency;
  String? receipt;
  String? offerId;
  String? status;
  int? attempts;
  List<PaymentDetailResponseNotes?>? notes;
  int? createdAt;

  PaymentDetailModel({
    this.id,
    this.entity,
    this.amount,
    this.amountPaid,
    this.amountDue,
    this.currency,
    this.receipt,
    this.offerId,
    this.status,
    this.attempts,
    this.notes,
    this.createdAt,
  });
  PaymentDetailModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    entity = json['entity']?.toString();
    amount = json['amount']?.toInt();
    amountPaid = json['amount_paid']?.toInt();
    amountDue = json['amount_due']?.toInt();
    currency = json['currency']?.toString();
    receipt = json['receipt']?.toString();
    offerId = json['offer_id']?.toString();
    status = json['status']?.toString();
    attempts = json['attempts']?.toInt();
    if (json['notes'] != null) {
      final v = json['notes'];
      final arr0 = <PaymentDetailResponseNotes>[];
      v.forEach((v) {
        arr0.add(PaymentDetailResponseNotes.fromJson(v));
      });
      notes = arr0;
    }
    createdAt = json['created_at']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['entity'] = entity;
    data['amount'] = amount;
    data['amount_paid'] = amountPaid;
    data['amount_due'] = amountDue;
    data['currency'] = currency;
    data['receipt'] = receipt;
    data['offer_id'] = offerId;
    data['status'] = status;
    data['attempts'] = attempts;
    if (notes != null) {
      final v = notes;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['notes'] = arr0;
    }
    data['created_at'] = createdAt;
    return data;
  }
}
